### PR TITLE
+Fix Issues 7, 8, 9, & 10

### PR DESCRIPTION
**Pull request by keni8em**

### CODE REVIEW

**Comment by mark-hahn** [comment]
I'm sorry but I haven't used Atom in 2 or 3 years.  If you want, I can
transfer ownership of this project to you, just tell me how.

P.S. Have you tried VSCode?  It is superior in most ways,

**Comment by keni8em** [comment]
Hi Mark,

I’m fine with that. Go into the repository settings and click on transfer to username keni8em.
I have not tried VSC, however I do have it installed. Might give it a try.

Regards,
Kenneth



On 23 Feb 2021, at 18:08, Mark Hahn <notifications@github.com<mailto:notifications@github.com>> wrote:


[EXTERNAL EMAIL]

I'm sorry but I haven't used Atom in 2 or 3 years. If you want, I can
transfer ownership of this project to you, just tell me how.

P.S. Have you tried VSCode? It is superior in most ways,

**Comment by mark-hahn** [comment]
I got "keni8em/drag-drop-text already exists".

You really should try vscode.  It is night-and-day better.  And I was an
expert on atom.

**Comment by keni8em** [comment]
That’s because I had created a fork of yours, my apologies.
I have cleared it out, so you should be able to transfer now.

I am definitely going to look at VSC.
My main use-case was Latex publications, and I see VSC has extensions for do those.

Regards,
Kenneth


On 23 Feb 2021, at 21:49, Mark Hahn <notifications@github.com<mailto:notifications@github.com>> wrote:


[EXTERNAL EMAIL]

I got "keni8em/drag-drop-text already exists".

You really should try vscode. It is night-and-day better. And I was an
expert on atom.

**Comment by mark-hahn** [comment]
Transferred.

**Comment by keni8em** [comment]
As soon as the transfer confirmation arrives from Github, I will accept the transfer and it will move from your account to mine.

Thank you.
Kenneth.



On 24 Feb 2021, at 00:11, Mark Hahn <notifications@github.com<mailto:notifications@github.com>> wrote:


[EXTERNAL EMAIL]

Transferred.

**Pull request closed without merging**
